---
sidebar: sidebar 
permalink: reference-configs-gcp.html 
keywords: google, gcp, google cloud platform, explore, standard, premium, byol, paygo, disks, supported, capacity, machine types, sizes, HA, high availability, HA pairs 
summary: Sono supportate diverse configurazioni di Cloud Volumes ONTAP in Google Cloud. 
---
= Configurazioni supportate per Cloud Volumes ONTAP in Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sono supportate diverse configurazioni di Cloud Volumes ONTAP in Google Cloud.



== Configurazioni supportate dalla licenza

Cloud Volumes ONTAP è disponibile in Google Cloud come sistema a nodo singolo e come coppia HA di nodi per la tolleranza agli errori e le operazioni senza interruzioni.

L'aggiornamento di un sistema a nodo singolo a una coppia HA non è supportato. Se si desidera passare da un sistema a nodo singolo a una coppia HA, è necessario implementare un nuovo sistema e replicare i dati dal sistema esistente al nuovo sistema.

Cloud Volumes ONTAP può essere eseguito su una istanza di macchine virtuali Reserved o On-demand del tuo cloud provider. Le soluzioni che utilizzano altri tipi di istanze di macchine virtuali non sono supportate.

[role="tabbed-block"]
====
.Licenze basate sulla capacità
--
[cols="h,d,d,d"]
|===
|  | Freemium | Ottimizzato ^4^ | Licenza basata sulla capacità (Essentials e Professional) 


| Capacità massima del sistema (dischi + storage a oggetti) | 500 GiB  a| 
Con il modello di licensing basato sulla capacità, ogni sistema Cloud Volumes ONTAP supporta il tiering verso storage a oggetti. La capacità totale suddivisa in livelli può essere scalata fino al limite di bucket del cloud provider. Sebbene la licenza non imponga restrizioni di capacità, dovresti seguire le  https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Best practice per FabricPool"^] per garantire prestazioni, affidabilità ed efficienza dei costi ottimali durante la configurazione e la gestione del tiering.



| Tipi di macchine supportati ^1^  a| 
* n1-standard-8 ^1^
* n1-standard-32 ^1^
* n2-standard-4
* n2-standard-8
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64

 a| 
* n2-standard-4
* n2-standard-8

 a| 
* n1-standard-8 ^1^
* n1-standard-32 ^1^
* n2-standard-4
* n2-standard-8
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64




| Tipi di disco supportati ^2^ 3+| Dischi persistenti bilanciati ^3^, dischi persistenti Performance (SSD) ^3^ e dischi persistenti Standard (HDD). 
|===
Note:

. ^1^ Le macchine della serie n1 non sono più disponibili per la selezione sulla NetApp Console quando si distribuiscono nuove istanze di Cloud Volumes ONTAP in Google Cloud. Le macchine della serie n1 saranno mantenute e supportate solo nei sistemi esistenti più vecchi. Le nuove distribuzioni di Cloud Volumes ONTAP sono supportate in Google Cloud solo dalla release 9.8. Si consiglia di passare alle macchine della serie n2 compatibili con Cloud Volumes ONTAP 9.8 e versioni successive. Le macchine della serie n1, tuttavia, saranno disponibili per le nuove distribuzioni effettuate tramite l'API.
+
Il tipo di macchina custom-4-16384 non è più supportato con i nuovi sistemi Cloud Volumes ONTAP. Se si dispone di un sistema esistente in esecuzione su questo tipo di macchina, è possibile continuare a utilizzarlo, ma si consiglia di passare al tipo di macchina n2-standard-4.

. ^2^ I limiti del disco possono impedire di raggiungere il limite massimo di capacità del sistema utilizzando solo i dischi. È possibile raggiungere il limite di capacità tramite  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["suddivisione in livelli dei dati inattivi su storage a oggetti"^].
+
link:reference-limits-gcp.html["Scopri di più sui limiti del disco in Google Cloud"].

. ^3^ Le prestazioni di scrittura migliorate sono abilitate quando si utilizzano dischi persistenti Balanced e dischi persistenti Performance (SSD).
+
A partire da Cloud Volumes ONTAP 9.13.0, _Flash Cache_, elevata velocità di scrittura e un'unità di trasmissione massima (MTU) più elevata di 8.896 byte sono disponibili per le seguenti istanze di distribuzione di coppia HA:

+
** n2-standard-16
** n2-standard-32
** n2-standard-48
** n2-standard-64
+
È possibile abilitare _Flash Cache_ e un'elevata velocità di scrittura durante la distribuzione di un tipo di istanza idoneo. Per abilitare l'unità di trasmissione massima più elevata di 8.896 byte, è necessario scegliere VPC-1, VPC-2 o VPC-3 per la distribuzione. L'MTU più elevato consente un throughput di rete maggiore. Per ulteriori informazioni sull'avvio di una di queste distribuzioni, vedere  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Avvio di una coppia HA in Google Cloud"].

+

NOTE: _Flash cache_, modalità di scrittura elevata e un MTU di 8.896 dipendono dalle funzionalità e non possono essere disabilitati singolarmente all'interno di un'istanza configurata.



. ^4^ A partire dall'11 agosto 2025, la licenza Cloud Volumes ONTAP Optimized sarà deprecata e non sarà più disponibile per l'acquisto o il rinnovo nel marketplace di Google Cloud per abbonamenti pay-as-you-go (PAYGO). Per informazioni, consultare  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Novità in Cloud Volumes ONTAP"^].


--
.Licenze basate su nodi
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explore | PAYGO Standard | PAYGO Premium | BYOL basato su nodi 


| Capacità massima del sistema (dischi + storage a oggetti) | 2 TB ^2^ | 10 TiB | 368 TiB | 368 TiB per licenza 


| Tipi di macchine supportate ^3^  a| 
* n2-standard-4

 a| 
* n1-standard-8 ^3^
* n2-standard-8

 a| 
* n1-standard-32 ^3^
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64

 a| 
* n1-standard-8 ^3^
* n1-standard-32 ^3^
* n2-standard-4
* n2-standard-8
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64




| Tipi di disco supportati 4+| Dischi persistenti bilanciati ^4^, dischi persistenti Performance (SSD) ^4^ e dischi persistenti Standard (HDD). 
|===
Note:

. ^1^ I limiti del disco possono impedire di raggiungere il limite massimo di capacità del sistema utilizzando solo i dischi. È possibile raggiungere il limite di capacità  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["suddivisione in livelli dei dati inattivi su storage a oggetti"^].
+
link:reference-limits-gcp.html["Scopri di più sui limiti del disco in Google Cloud"].

. ^2^ Il tiering dei dati su Google Cloud Storage non è supportato con PAYGO Explore.
. ^3^ Le macchine della serie n1 non sono più disponibili per la selezione nella Console durante la distribuzione di nuove istanze di Cloud Volumes ONTAP in Google Cloud. Le macchine della serie n1 saranno mantenute e supportate solo nei sistemi esistenti più vecchi. Le nuove distribuzioni di Cloud Volumes ONTAP sono supportate in Google Cloud solo dalla release 9.8. Si consiglia di passare alle macchine della serie n2 che sono compatibili con Cloud Volumes ONTAP 9.8 e versioni successive. Le macchine della serie n1, tuttavia, saranno disponibili per le nuove distribuzioni eseguite tramite l'API.
+
Il tipo di macchina custom-4-16384 non è più supportato con i nuovi sistemi Cloud Volumes ONTAP. Se si dispone di un sistema esistente in esecuzione su questo tipo di macchina, è possibile continuare a utilizzarlo, ma si consiglia di passare al tipo di macchina n2-standard-4.

. ^4^ Le prestazioni di scrittura migliorate sono abilitate quando si utilizzano dischi persistenti Balanced e dischi persistenti Performance (SSD).


La Console mostra un ulteriore tipo di macchina supportato per Standard e BYOL: n1-highmem-4. Tuttavia, questo tipo di macchina non è pensato per gli ambienti di produzione. Lo abbiamo reso disponibile solo per uno specifico ambiente di laboratorio.

A partire dalla versione 9.13.0 del software Cloud Volumes ONTAP, _Flash Cache_, elevata velocità di scrittura e un'unità di trasmissione massima (MTU) di 8.896 byte sono disponibili per le seguenti istanze di distribuzione di coppia HA:

* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64


È possibile abilitare _Flash Cache_ e un'elevata velocità di scrittura durante la distribuzione di un tipo di istanza idoneo. Per abilitare l'unità di trasmissione massima più elevata di 8.896 byte, è necessario scegliere VPC-1, VPC-2 o VPC-3 per la distribuzione. L'MTU più elevato consente un throughput di rete maggiore. Per ulteriori informazioni sull'avvio di una di queste distribuzioni, vedere  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Avvio di una coppia HA in Google Cloud"].


NOTE: _Flash cache_, modalità di scrittura elevata e un MTU di 8.896 dipendono dalle funzionalità e non possono essere disabilitati singolarmente all'interno di un'istanza configurata.

--
====
Per ulteriori informazioni sui tipi di macchine specifici, consultare la documentazione di Google Cloud:

* https://cloud.google.com/compute/docs/general-purpose-machines#n1_machines["tipi di macchine generiche della serie n1"^]
* https://cloud.google.com/compute/docs/general-purpose-machines#n2_series["Tipi di macchine generiche della serie N2"^]




== Dimensioni del disco supportate

In Google Cloud, un aggregato può contenere fino a 6 dischi che sono tutti dello stesso tipo e dimensione. Sono supportate le seguenti dimensioni di disco:

* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 8 TB
* 16 TB
* 64 TB




== Regioni supportate

Per il supporto delle regioni di Google Cloud, vedere https://bluexp.netapp.com/cloud-volumes-global-regions["Regioni globali di Cloud Volumes"^].
