---
sidebar: sidebar 
permalink: reference-configs-aws.html 
keywords: ec2, instance, type, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations, sizes, disks, networking, bandwidth, professional package 
summary: Sono supportate diverse configurazioni di Cloud Volumes ONTAP in AWS. 
---
= Configurazioni supportate per Cloud Volumes ONTAP in AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sono supportate diverse configurazioni di Cloud Volumes ONTAP in AWS.



== Numero di nodi supportati

Cloud Volumes ONTAP è disponibile in AWS come sistema a nodo singolo e come coppia HA di nodi per tolleranza agli errori e operazioni senza interruzioni.

L'aggiornamento di un sistema a nodo singolo a una coppia HA non è supportato. Se si desidera passare da un sistema a nodo singolo a una coppia HA, è necessario implementare un nuovo sistema e replicare i dati dal sistema esistente al nuovo sistema.



== Storage supportati

Cloud Volumes ONTAP supporta diversi tipi di dischi EBS e storage a oggetti S3 per il data tiering. La capacità di storage massima è determinata dalla licenza che si sceglie.



=== Supporto dello storage tramite licenza

Ogni licenza supporta una diversa capacità massima del sistema. La capacità massima del sistema include l'archiviazione su disco più lo storage a oggetti utilizzato per il tiering dei dati. NetApp non supporta il superamento di questo limite.

[role="tabbed-block"]
====
.Licenze basate sulla capacità
--
[cols="h,d,d"]
|===
|  | Freemium | Licenza basata sulla capacità 


 a| 
*Capacità massima del sistema* (dischi + storage a oggetti) ^1^
| 500 GiB | Flessibile ^2^ 


 a| 
*Tipi di disco supportati*
 a| 
* SSD per uso generale (gp3 e gp2) ^3^,^5^
* SSD IOPS con provisioning (io1) ^3^
* HDD con throughput ottimizzato (st1) ^4^




 a| 
*Tiering dei dati a freddo su S3*
 a| 
Supportato

|===
Note:

. Per una coppia HA, il limite di capacità si riferisce all'intera coppia HA. Non è per nodo. Ad esempio, se si utilizza la licenza Premium, è possibile avere fino a 368 TiB di capacità tra entrambi i nodi.
. In alcune configurazioni, i limiti del disco impediscono di raggiungere il limite di capacità utilizzando solo i dischi. In questi casi, è possibile raggiungere il limite di capacità mediante  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["suddivisione in livelli dei dati inattivi su storage a oggetti"^]. Per informazioni sui limiti del disco, fare riferimento a link:reference-limits-aws.html["limiti di storage"].
+
Con il modello di licensing basato sulla capacità, ogni sistema Cloud Volumes ONTAP supporta il tiering verso storage a oggetti. La capacità totale suddivisa in livelli può essere scalata fino al limite di bucket del cloud provider. Sebbene la licenza non imponga restrizioni di capacità, dovresti seguire le  https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Best practice per FabricPool"^] per garantire prestazioni, affidabilità ed efficienza dei costi ottimali durante la configurazione e la gestione del tiering.

. Le prestazioni di scrittura migliorate sono abilitate quando si utilizzano SSD con tutte le configurazioni Cloud Volumes ONTAP.
. Non è consigliato eseguire il tiering dei dati verso lo storage a oggetti quando si utilizzano Throughput Optimized HDDs (st1).
. Le configurazioni di Cloud Volumes ONTAP in AWS Local Zones supportano solo il tipo di disco General Purpose SSD (gp2). Nessun altro tipo di disco è supportato in Cloud Volumes ONTAP in AWS Local Zones.


--
.Licenze basate su nodi
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explore | PAYGO Standard | PAYGO Premium | BYOL basato su nodi 


| Capacità massima del sistema (dischi + storage a oggetti) | 2 TiB | 10 TiB | 368 TiB ^2^ | 368 TiB per licenza ^2^ 


| Tipi di disco supportati  a| 
* SSD per uso generale (gp3 e gp2) ^3^,^5^
* SSD IOPS con provisioning (io1) ^3^
* HDD con throughput ottimizzato (st1) ^4^




| Tiering dei dati cold su S3 | Non supportato 3+| Supportato 
|===
Note:

. Per una coppia HA, il limite di capacità si riferisce all'intera coppia HA. Non è per nodo. Ad esempio, se si utilizza la licenza Premium, è possibile avere fino a 368 TiB di capacità tra entrambi i nodi.
. In alcune configurazioni, i limiti del disco impediscono di raggiungere il limite di capacità utilizzando solo i dischi. In questi casi, è possibile raggiungere il limite di capacità mediante  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["suddivisione in livelli dei dati inattivi su storage a oggetti"^]. Per informazioni sui limiti del disco, fare riferimento a link:reference-limits-aws.html["limiti di storage"].
. Le prestazioni di scrittura migliorate sono abilitate quando si utilizzano SSD con tutte le configurazioni Cloud Volumes ONTAP, ad eccezione di PAYGO Explore.
. Non è consigliato eseguire il tiering dei dati verso lo storage a oggetti quando si utilizzano Throughput Optimized HDDs (st1).
. Le configurazioni di Cloud Volumes ONTAP nelle AWS Local Zones supportano solo il tipo di disco General Purpose SSD (gp2).


--
====


=== Dimensioni del disco supportate

In AWS, un aggregato può contenere fino a 6 dischi tutti della stessa dimensione. Ma se si dispone di una configurazione che supporta la funzionalità Amazon EBS Elastic Volumes, allora un aggregato può contenere fino a 8 dischi. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["Scopri di più sul supporto per Elastic Volumes"^]

[cols="3*"]
|===
| SSD per uso generale (gp3 e gp2) | Provisioned IOPS SSD (io1) | HDD ottimizzati per il throughput (st1) 


 a| 
* 100 GiB
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB

 a| 
* 100 GiB
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB

 a| 
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB


|===


== Calcolo EC2 supportato

Ogni licenza Cloud Volumes ONTAP supporta diversi tipi di istanze EC2. Per comodità, la tabella seguente mostra i valori di vCPU, RAM e larghezza di banda per ciascun tipo di istanza supportato. https://aws.amazon.com/ec2/instance-types/["Dovresti fare riferimento ad AWS per i dettagli più recenti e completi sui tipi di istanza EC2"^]

Cloud Volumes ONTAP può essere eseguito su una istanza EC2 riservata o on-demand. Le soluzioni che utilizzano altri tipi di istanze non sono supportate.

Le larghezze di banda indicate nella tabella sottostante corrispondono ai limiti AWS documentati per ciascun tipo di istanza. Questi limiti non sono completamente in linea con quanto Cloud Volumes ONTAP può fornire. Per le prestazioni previste, fare riferimento a https://www.netapp.com/pdf.html?item=/media/9088-tr4383pdf.pdf["NetApp Technical Report 4383: Caratterizzazione delle prestazioni di Cloud Volumes ONTAP in Amazon Web Services con carichi di lavoro applicativi"^].

[cols="8*"]
|===
| Licenza | Istanza supportata | vCPU | RAM | Flash Cache ^1^ | larghezza di banda (Gbps) | EBS larghezza di banda (Mbps) | Alta velocità di scrittura ^2^ 


| *Explore o qualsiasi altra licenza* | m5.xlarge ^6^ | 4 | 16 | Non supportato | Fino a 10 | Fino a 4,750 | Supportato (solo nodo singolo) 


.3+| *Licenza standard o qualsiasi altra licenza* | r5.xlarge ^6^ | 4 | 32 | Non supportato | Fino a 10 | Fino a 4,750 | Supportato (solo nodo singolo) 


| m5a.2xlarge | 8 | 32 | Non supportato | Fino a 10 | Fino a 2,880 | Supportato 


| m5.2xlarge ^6^ | 8 | 32 | Non supportato | Fino a 10 | Fino a 4,750 | Supportato 


.22+| *Licenza Premium o qualsiasi altra licenza* | m5n.2xlarge | 8 | 32 | Non supportato | Fino a 25 | Fino a 4,750 | Supportato 


| r5.2xlarge ^6^ | 8 | 64 | Non supportato | Fino a 10 | Fino a 4,750 | Supportato 


| r5d.2xlarge | 8 | 64 | Supportato | Fino a 10 | Fino a 4,750 | Supportato 


| c5d.4xlarge ^6^ | 16 | 32 | Supportato | Fino a 10 | 4.570 | Supportato 


| m5.4xlarge ^6^ | 16 | 64 | Non supportato | Fino a 10 | 4.750 | Supportato 


| m5dn.4xlarge | 16 | 64 | Supportato | Fino a 25 | 4.750 | Supportato 


| m5d.8xlarge | 32 | 128 | Supportato | 10 | 6.800 | Supportato 


| r5.8xlarge | 32 | 256 | Non supportato | 10 | 6.800 | Supportato 


| c5.9xlarge | 36 | 72 | Non supportato | 10 | 9.500 | Supportato 


| c5d.9xlarge | 36 | 72 | Supportato | 10 | 9.500 | Supportato 


| c5n.9xlarge | 36 | 96 | Non supportato | 50 | 9.500 | Supportato 


| c5a.12xlarge | 48 | 96 | Non supportato | 12 | 4.750 | Supportato 


| c5.18xlarge | 64 ^4^ | 144 | Non supportato | 25 | 19.000 | Supportato 


| c5d.18xlarge | 64 ^4^ | 144 | Supportato | 25 | 19.000 | Supportato 


| m5d.12xlarge | 48 | 192 | Supportato | 12 | 9.500 | Supportato 


| m5dn.12xlarge | 48 | 192 | Supportato | 50 | 9.500 | Supportato 


| c5n.18xlarge | 64 ^4^ | 192 | Non supportato | 100 | 19.000 | Supportato 


| m5a.16xlarge | 64 | 256 | Non supportato | 12 | 9.500 | Supportato 


| m5.16xlarge | 64 | 256 | Non supportato | 20 | 13.600 | Supportato 


| r5.12xlarge ^3^ | 48 | 384 | Non supportato | 10 | 9.500 | Supportato 


| m5dn.24xlarge | 64 ^4^ | 384 | Supportato | 100 | 19.000 | Supportato 


| m6id.32xlarge | 64 ^4^ | 512 | Supportato | 50 | 40.000 | Supportato 
|===
. Alcuni tipi di istanza includono storage NVMe locale, che Cloud Volumes ONTAP utilizza come _Flash Cache_. Flash Cache velocizza l'accesso ai dati tramite caching intelligente in real-time dei dati utente letti di recente e dei metadati NetApp. È efficace per carichi di lavoro ad alta intensità di lettura casuale, inclusi database, email e servizi file. La compressione deve essere disabilitata su tutti i volumi per sfruttare i miglioramenti delle prestazioni di Flash Cache. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["Scopri di più su Flash Cache"^]
. Cloud Volumes ONTAP supporta un'elevata velocità di scrittura con la maggior parte dei tipi di istanza quando si utilizza una coppia HA. L'elevata velocità di scrittura è supportata con tutti i tipi di istanza quando si utilizza un sistema a nodo singolo. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["Scopri di più sulla scelta della velocità di scrittura"^]
. Il tipo di istanza r5.12xlarge presenta una limitazione nota in termini di supporto. Se un nodo si riavvia inaspettatamente a causa di un errore di sistema, il sistema potrebbe non raccogliere i file core utilizzati per la risoluzione dei problemi e per individuarne la causa principale. Il cliente accetta i rischi e i termini di supporto limitato e si assume ogni responsabilità in merito al supporto se si verifica questa condizione. Questa limitazione riguarda le coppie HA appena distribuite e le coppie HA aggiornate da 9.8. La limitazione non riguarda i sistemi a nodo singolo appena distribuiti.
. Mentre questi tipi di istanza EC2 supportano più di 64 vCPU, Cloud Volumes ONTAP supporta solo fino a 64 vCPU.
. Quando si sceglie un tipo di istanza EC2, è possibile specificare se si tratta di un'istanza condivisa o di un'istanza dedicata.
. Le AWS Local Zones sono supportate nelle seguenti famiglie di tipi di istanze EC2 con dimensioni da xlarge a 4xlarge: M5, C5, C5d, R5 e R5d. link:https://aws.amazon.com/about-aws/global-infrastructure/localzones/features/?nc=sn&loc=2["Dovresti fare riferimento ad AWS per i dettagli più recenti e completi sui tipi di istanze EC2 supportati nelle Local Zones"^].
+
L'elevata velocità di scrittura non è supportata con questi tipi di istanze in AWS Local Zones.





=== Le istanze c4, m4 e r4 non sono più supportate

Cloud Volumes ONTAP non supporta più i tipi di istanza EC2 c4, m4 e r4 in AWS. Se il sistema è in esecuzione su un'istanza c4, m4 o r4, cambiare a un'istanza c5, m5 o r5. Non è possibile eseguire l'aggiornamento a questa release finché non si modifica il tipo di istanza.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Scopri come modificare il tipo di istanza EC2 per Cloud Volumes ONTAP"^].

Per maggiori informazioni, fare riferimento a:

* https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Converting_an_AWS_Xen_CVO_instance_to_Nitro_KVM["Articolo della Knowledge base (KB): Conversione di un'istanza CVO di AWS Xen in Nitro KVM"^]
* https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Unable_to_change_the_instance_type_from_r4_to_r5_with_disk_count_error["KB article: Impossibile modificare il tipo di istanza da r4 a r5 con errore di conteggio dei dischi"^]
* link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Scopri di più sulla fine della disponibilità e del supporto per questi tipi di istanza"^]




== Regioni supportate

Per il supporto della regione AWS, vedere https://bluexp.netapp.com/cloud-volumes-global-regions["Regioni globali di Cloud Volumes"^].
